### ISSUE TITLE
openpose command

### ISSUE THREAD

**Issue by sdy-ny** [pixelite1201/agora_evaluation#11]
Hi, could you share the OpenPose parameters you used to detect persons, so that the detector is not the reason for low performance?

I am using the following parameters on the validation set. However, it is only able to detect 3505 persons, where as the number of persons according to the validation ground truth dataframes, is 7800+. So if I evaluate on validation set, the recall is really bad. 

`--face --hand --net_resolution "272x-1" --scale_number 4 --scale_gap 0.25 --hand_scale_number 6 --hand_scale_range 0.4 --render_pose 0 --number_people_max 15`

**Comment by pixelite1201** [comment]
Hello,
We use following parameters for openpose detections:
`  params["hand"] = True`
   ` params["face"] = True`
    `params['net_resolution']= "-1x272"`
    `params["scale_number"]=2`
   ` params["scale_gap"]=0.25`
Rest of the parameters are set to default.

For SPIN-ft on validation set there are the numbers for precision and recall:
`'precision': 0.91, 'recall': 0.64, 'f1': 0.75`
