### ISSUE TITLE
how to download data with command line?

### ISSUE THREAD

**Issue by xuxy09** [pixelite1201/agora_evaluation#12]
Hi,

I want to download the dataset with Ubuntu command line. When I try to "wget https://psfiles.is.tuebingen.mpg.de/downloads/agora/train_images_1280x720_0-zip", I got a no-permission error. 

I have registered an account on the dataset website, could you show me how to wget the dataset by passing the userid and password?

Thanks!

**Comment by pixelite1201** [comment]
It is not possible to download the file with the link. As you can also see in the error message that you get when you try this: "Please keep in mind that all downloads are blocked if they are not started from the website directly."
The reason for this is to prevent downloading  of data without going through the license.
