### ISSUE TITLE
Global rotation in camera coordinate

### ISSUE THREAD

**Issue by zhihaolee** [pixelite1201/agora_evaluation#14]
Could you share the code to get the global rotation of SMPL in camera coordinate? Thank you very much!

**Comment by pixelite1201** [comment]
Hello,
please check out following function to see how you can transform from world coordinate to camera coordinates.
https://github.com/pixelite1201/agora_evaluation/blob/master/agora_evaluation/get_joints_verts_from_dataframe.py#L177

**Comment by zhihaolee** [comment]
Thanks for your quick response! 
I've written some code referring to these functions, for some images, it works well, but for the others, it doesn't. 
I get the global rotation, and use PnP to get the camera translation for rendering as SPIN does, for some images, the rendered mesh can't match the image and the projected joints from your code. The problem seems only happened for those whose name have cam00, cam01, cam02…., CamPitch is not zero, but not for hdri…, CamPitch is zero.
Do you know why?

**Comment by pixelite1201** [comment]
For cam0* images, both camera yaw and pitch are present. And the order matters so make sure that first you rotate with camera yaw and then cam pitch.

**Comment by zhihaolee** [comment]
Sorry for the late reply!
I found out the root cause of the problem is that I didn't use the GT focal length in PnP estimation, after changing to the GT focal length, everything goes well.
Thank you!
