### ISSUE TITLE
how SMPL params in cam convert?

### ISSUE THREAD

**Issue by Gzzgz** [pixelite1201/agora_evaluation#16]
I used root_pose like this:
![图片](https://user-images.githubusercontent.com/15968092/156723788-9e2b8160-e3a6-49c8-9604-ca8c4d4f64ba.png)
and the res like :
<img width="610" alt="图片" src="https://user-images.githubusercontent.com/15968092/156723642-cd69ba90-7132-4b9f-9645-53d4e02efb53.png">

**Comment by He-Chao** [comment]
how to get correct smpl pose global_orient?
![image](https://user-images.githubusercontent.com/38954558/224605938-b408860b-44bd-459f-a495-4bf1e5bc0e08.png)
![epoch_0_iter_0_train_4_8](https://user-images.githubusercontent.com/38954558/224605948-b5b94c60-00e2-45a0-bcda-4183acb1cd08.jpg)

**Comment by oscarfossey** [comment]
Hello, does anyone of you succeed to transform "global_orient" into the camera coordinates?

**Comment by mayank64ce** [comment]
not yet :(

**Comment by ShamLich** [comment]
same problem

**Comment by pixelite1201** [comment]
Please check out the processing code here: https://github.com/pixelite1201/agora_evaluation/tree/master/agora_processing_code
