### ISSUE TITLE
Many images are missing in the 3840x2160 training split

### ISSUE THREAD

**Issue by mks0601** [pixelite1201/agora_evaluation#2]
Hi, I found that most of images are missing in the 3840x2160 training split.
On the other hand, all images can be found in 1280x720 training split.
Here is a code to check the missing images.
You can run this code in the below directory
$(PWD)
|-- Cam
|-- |-- train_0.pkl
|-- |-- train_1.pkl
|-- |-- train_2.pkl
|-- |-- train_3.pkl
|-- |-- train_4.pkl
|-- |-- train_5.pkl
|-- |-- train_6.pkl
|-- |-- train_7.pkl
|-- |-- train_8.pkl
|-- |-- train_9.pkl
|-- train_0 (a folder that contains 3840x2160 images)
|-- train_1 (a folder that contains 3840x2160 images)
|-- train_2 (a folder that contains 3840x2160 images)
|-- train_3 (a folder that contains 3840x2160 images)
|-- train_4 (a folder that contains 3840x2160 images)
|-- train_5 (a folder that contains 3840x2160 images)
|-- train_6 (a folder that contains 3840x2160 images)
|-- train_7 (a folder that contains 3840x2160 images)
|-- train_8 (a folder that contains 3840x2160 images)
|-- train_9 (a folder that contains 3840x2160 images)
```
import os.path as osp
from glob import glob
import pickle

data_path_list = glob(osp.join('Cam', 'train*'))
for data_path in data_path_list:
    with open(data_path, 'rb') as f:
        data = pickle.load(f, encoding='latin1')
        data = {k: list(v) for k,v in data.items()}
    folder_name = data_path.split('/')[-1][:-4] # train_0

    for i in range(len(data['imgPath'])):
        img_path_gt = data['imgPath'][i]
        img_path = osp.join(folder_name, img_path_gt)
        if not osp.isfile(img_path):
            print(img_path)
```

**Comment by pixelite1201** [comment]
Thanks for pointing this out. There was a mismatch in folder naming. I uploaded the images again with correct folder. You can download them from the agora.is.tue.mpg.de.

**Comment by pixelite1201** [comment]
Just the 3840x2160 images.

**Comment by mks0601** [comment]
Thanks!
