### ISSUE TITLE
Any instructions on how render SMPL bodies in Unreal?

### ISSUE THREAD

**Issue by kristijanbartol** [pixelite1201/agora_evaluation#20]
Hi, thank you very much for providing the dataset, parameters, and these evaluation instructions. I would like to use your parameters to generate the bodies myself using Blender and Unreal Engine.

Do you have any additional instructions / scripts on how to do it more automatically, especially in Unreal where Python scripting is not that straightforward?

So far, I've figured out I could use SMPL-X plugin and Python scripting in Blender to generate the SMPL-X bodies following your parameters, however, the Unreal part is a bit more complicated, especially as I have zero experience using it. I guess that using C++ is more convenient than Python in Unreal, so I also have to figure out how to make it work all together.

I would greatly appreciate any help or brief advice! Thank you!

**Comment by tpsmpi** [comment]
Here is one option to do this:
1. Generate posed SMPL-X bodies and save in OBJ format. You can do this either through custom Python code using the official SMPL-X Python release or with Blender through our SMPL-X Blender add-on [1]. Remember that you can script Blender with Python for further automation.
2. Import OBJ files into Unreal as StaticMesh
3. Add StaticMesh to target scene in Unreal. This can be done either through Unreal Python or Blueprint. You can also use C++ but it is not necessary for this task.

[1] https://smpl-x.is.tue.mpg.de/

**Comment by kristijanbartol** [comment]
Thank you very much for providing the option. In the meantime, we have found some ways to work with the meshes in Blender/Unreal. I also suggest using the [send2unreal plugin](https://epicgames.github.io/BlenderTools/send2ue/) for a potentially more automatic pipeline.
