### ISSUE TITLE
Equation 4 in the paper look wrong?

### ISSUE THREAD

**Issue by ericchang1997** [pixelite1201/agora_evaluation#3]
The Eq. 4 in the paper doesn't look intuitive. Why the probability is square-rooted and inside the robustifier? 
Is it just a typo or there's an explanation for this?

**Comment by pixelite1201** [comment]
Eq. 4 is what we used for fitting. We also try the more intuitive solution and compare them as shown in Figure 8 in the paper. We found that the difference in accuracy of the fitting for the two design choice is negligible so we stick with Eq. 4.

**Comment by ParthaEth** [comment]
Totally agreed @ericchang1997. Can you pls elaborate?
