### ISSUE TITLE
Leaderboard 

### ISSUE THREAD

**Issue by mks0601** [pixelite1201/agora_evaluation#4]
Hi,

I uploaded my results on the evaluation server, but I can't make it public after getting this mail.

```
This submission has an unexpected score and it is automatically forwarded for an additional check by a website administrator. 
The submission process at the moment is suspended until one of the administrators approves this submission for publishing. 
You will be additionally notified when this happens through a separate email. Thank you for your understanding.
```
My submission email address is mks0601@snu.ac.kr
Could you check?
Thanks

**Comment by pixelite1201** [comment]
Hi,
As said in the mail, the result will be verified and once approved, it will be available for uploading. Also, for leaderboard related issue, it will be better if you mail to the contact information provided on https://agora-evaluation.is.tuebingen.mpg.de/. This way it will reach to the the team maintaining the leaderboard and would be resolve faster.
