### ISSUE TITLE
correspondence between SMPLX and SMPL annotations

### ISSUE THREAD

**Issue by mks0601** [pixelite1201/agora_evaluation#5]
Hi,
I'd like to ask correspondence between SMPLX and SMPL annotations.

```
with open('SMPL/train_0_withjv.pkl', 'rb') as f:
    data_smpl = pickle.load(f, encoding='latin1')
    data_smpl = {k: list(v) for k,v in data_smpl.items()}

with open('SMPLX/train_0_withjv.pkl', 'rb') as f:
    data_smplx = pickle.load(f, encoding='latin1')
    data_smplx = {k: list(v) for k,v in data_smplx.items()}
```

`data_smpl['gt_joints_2d'][image_id][person_id]` always represents the same person with `data_smplx['gt_joints_2d'][image_id][person_id]`?

**Comment by pixelite1201** [comment]
Yes. Since both SMPL/train* and SMPLX/train* are generated using Cam/train*, they always represent the same person.

**Comment by mks0601** [comment]
Thanks!
