### ISSUE TITLE
keypoints_3d meaning

### ISSUE THREAD

**Issue by dldaisy** [pixelite1201/agora_evaluation#6]
Hi,
I noticed a field naming `keypoints_3d` in `smplx_gt/datasetxxxx/modelxxxx.pkl` with shape [25, 3], which I don't find a counterpart in the model pkl file released by smplx(such as SMPLX_NEUTRAL.pkl). May I ask the meaning of this field? Thanks a lot!

**Comment by pixelite1201** [comment]
It is the first 25 joints of SMPLX model. This is just extra information that is stored in the .pkl file. You can ignore this field while loading the parameters.

**Comment by dldaisy** [comment]
I see. Thanks!
